all:
	@echo "[31;1mWorking on: OTHERS[m"
	@make --no-print-directory -C OTHERS
	@echo ""
	@echo "[31;1mWorking on: 1D_TRACING[m"
	@make --no-print-directory -C 1D_TRACING
	@echo ""
	@echo "[31;1mWorking on: 3D_MODEL[m"
	@make --no-print-directory -C 3D_MODEL
	@echo ""
	@echo "[31;1mWorking on: BENDING_LIN[m"
	@make --no-print-directory -C BENDING_LIN
	@echo ""
	@echo "[31;1mWorking on: BENDING_TELE[m"
	@make --no-print-directory -C BENDING_TELE
	@echo ""
	@echo "[31;1mWorking on: CONVERS[m"
	@make --no-print-directory -C CONVERS
	@echo ""
	@echo "[31;1mWorking on: CRUST[m"
	@make --no-print-directory -C CRUST
	@echo ""
	@echo "[31;1mWorking on: INVERS[m"
	@make --no-print-directory -C INVERS
	@echo ""
	@echo "[31;1mWorking on: RAYS_LOCATE[m"
	@make --no-print-directory -C RAYS_LOCATE
	@echo ""
	@echo "[31;1mWorking on: RAZNOE[m"
	@make --no-print-directory -C RAZNOE
	@echo ""
	@echo "[31;1mWorking on: SYNTH[m"
	@make --no-print-directory -C SYNTH
	@echo ""
	@echo "[31;1mWorking on: VISUAL[m"
	@make --no-print-directory -C VISUAL
	@echo ""

clean:
	@echo "[31;1mWorking on: OTHERS[m"
	@make --no-print-directory -C OTHERS clean
	@echo "[31;1mWorking on: 1D_TRACING[m"
	@make --no-print-directory -C 1D_TRACING clean
	@echo "[31;1mWorking on: 3D_MODEL[m"
	@make --no-print-directory -C 3D_MODEL clean
	@echo "[31;1mWorking on: BENDING_LIN[m"
	@make --no-print-directory -C BENDING_LIN clean
	@echo "[31;1mWorking on: BENDING_TELE[m"
	@make --no-print-directory -C BENDING_TELE clean
	@echo "[31;1mWorking on: CONVERS[m"
	@make --no-print-directory -C CONVERS clean
	@echo "[31;1mWorking on: CRUST[m"
	@make --no-print-directory -C CRUST clean
	@echo "[31;1mWorking on: INVERS[m"
	@make --no-print-directory -C INVERS clean
	@echo "[31;1mWorking on: RAYS_LOCATE[m"
	@make --no-print-directory -C RAYS_LOCATE clean
	@echo "[31;1mWorking on: RAZNOE[m"
	@make --no-print-directory -C RAZNOE clean
	@echo "[31;1mWorking on: SYNTH[m"
	@make --no-print-directory -C SYNTH clean
	@echo "[31;1mWorking on: VISUAL[m"
	@make --no-print-directory -C VISUAL clean
