#!/bin/bash

comp=""
for d in OTHERS 1D_TRACING  3D_MODEL  BENDING_LIN  BENDING_TELE  CONVERS  CRUST  INVERS RAYS_LOCATE  RAZNOE  SYNTH  VISUAL
do
 [ -d $d ] && echo "Working on: $d" || continue
 cd $d
 OBJ=`ls -1 *.f90 2> /dev/null | sed -e 's/.f90/.o/g' | tr "\n" " "`
 OBJ="$OBJ `ls -1 *.c 2> /dev/null | sed -e 's/.c/.o/g' | tr "\n" " "`"

 cat << EOF > Makefile
include ../../Makerules
OBJ=$OBJ

%.o:%.f90
	\$(FC) -c \$(FFLAGS) \$<

all: compile

compile: \$(OBJ)

clean:
	@rm -f \$(OBJ)
EOF
 comp="$comp $d"
 cd - > /dev/null
done


echo "all:" > Makefile
for d in $comp
do
 echo -e "\t@echo \"\e[31;1mWorking on: $d\e[m\"" >> Makefile
 echo -e "\t@make --no-print-directory -C $d" >> Makefile
 echo -e "\t@echo \"\"" >> Makefile
done

echo "" >> Makefile
echo "clean:" >> Makefile
for d in $comp
do
 echo -e "\t@echo \"\e[31;1mWorking on: $d\e[m\"" >> Makefile
 echo -e "\t@make --no-print-directory -C $d clean" >> Makefile
done

