all:
	@echo "[31;1mWorking on: GLOBUS[m"
	@make --no-print-directory -C GLOBUS
	@echo ""
	@echo "[31;1mWorking on: HOR_RESULT_NODES[m"
	@make --no-print-directory -C HOR_RESULT_NODES
	@echo ""
	@echo "[31;1mWorking on: RAY_DENSITY_HOR[m"
	@make --no-print-directory -C RAY_DENSITY_HOR
	@echo ""
	@echo "[31;1mWorking on: VARIANCE_REDUCTION[m"
	@make --no-print-directory -C VARIANCE_REDUCTION
	@echo ""
	@echo "[31;1mWorking on: VER_RESULT_NODES[m"
	@make --no-print-directory -C VER_RESULT_NODES
	@echo ""
	@echo "[31;1mWorking on: VIS_RAY_PATH[m"
	@make --no-print-directory -C VIS_RAY_PATH
	@echo ""
	@echo "[31;1mWorking on: VISUAL_3D_CUBE[m"
	@make --no-print-directory -C VISUAL_3D_CUBE
	@echo ""
	@echo "[31;1mWorking on: VISUAL_SYNINI_3D[m"
	@make --no-print-directory -C VISUAL_SYNINI_3D
	@echo ""
	@echo "[31;1mWorking on: RAY_DENSITY_HOR_NEW[m"
	@make --no-print-directory -C RAY_DENSITY_HOR_NEW
	@echo ""

clean:
	@echo "[31;1mWorking on: GLOBUS[m"
	@make --no-print-directory -C GLOBUS clean
	@echo "[31;1mWorking on: HOR_RESULT_NODES[m"
	@make --no-print-directory -C HOR_RESULT_NODES clean
	@echo "[31;1mWorking on: RAY_DENSITY_HOR[m"
	@make --no-print-directory -C RAY_DENSITY_HOR clean
	@echo "[31;1mWorking on: VARIANCE_REDUCTION[m"
	@make --no-print-directory -C VARIANCE_REDUCTION clean
	@echo "[31;1mWorking on: VER_RESULT_NODES[m"
	@make --no-print-directory -C VER_RESULT_NODES clean
	@echo "[31;1mWorking on: VIS_RAY_PATH[m"
	@make --no-print-directory -C VIS_RAY_PATH clean
	@echo "[31;1mWorking on: VISUAL_3D_CUBE[m"
	@make --no-print-directory -C VISUAL_3D_CUBE clean
	@echo "[31;1mWorking on: VISUAL_SYNINI_3D[m"
	@make --no-print-directory -C VISUAL_SYNINI_3D clean
	@echo "[31;1mWorking on: RAY_DENSITY_HOR_NEW[m"
	@make --no-print-directory -C RAY_DENSITY_HOR_NEW clean
