all:
	@echo "[31;1mWorking on: 0_REF_RAYS[m"
	@make --no-print-directory -C 0_REF_RAYS
	@echo ""
	@echo "[31;1mWorking on: 1_LOC_EVENT[m"
	@make --no-print-directory -C 1_LOC_EVENT
	@echo ""

clean:
	@echo "[31;1mWorking on: 0_REF_RAYS[m"
	@make --no-print-directory -C 0_REF_RAYS clean
	@echo "[31;1mWorking on: 1_LOC_EVENT[m"
	@make --no-print-directory -C 1_LOC_EVENT clean
