all:
	@echo "[31;1mWorking on: 0_SELECT_DATA[m"
	@make --no-print-directory -C 0_SELECT_DATA
	@echo ""
	@echo "[31;1mWorking on: 2_RAY_DENSITY[m"
	@make --no-print-directory -C 2_RAY_DENSITY
	@echo ""
	@echo "[31;1mWorking on: 4_TETRAD[m"
	@make --no-print-directory -C 4_TETRAD
	@echo ""
	@echo "[31;1mWorking on: 6_MATR[m"
	@make --no-print-directory -C 6_MATR
	@echo ""
	@echo "[31;1mWorking on: 8_3D_MODEL[m"
	@make --no-print-directory -C 8_3D_MODEL
	@echo ""
	@echo "[31;1mWorking on: A_SET_SYN_VER[m"
	@make --no-print-directory -C A_SET_SYN_VER
	@echo ""
	@echo "[31;1mWorking on: START_SYNTH[m"
	@make --no-print-directory -C START_SYNTH
	@echo ""
	@echo "[31;1mWorking on: 1_3D_LOCATE[m"
	@make --no-print-directory -C 1_3D_LOCATE
	@echo ""
	@echo "[31;1mWorking on: 3_GRID[m"
	@make --no-print-directory -C 3_GRID
	@echo ""
	@echo "[31;1mWorking on: 5_SOSEDI[m"
	@make --no-print-directory -C 5_SOSEDI
	@echo ""
	@echo "[31;1mWorking on: 7_INVERS[m"
	@make --no-print-directory -C 7_INVERS
	@echo ""
	@echo "[31;1mWorking on: A_SET_SYN_HOR[m"
	@make --no-print-directory -C A_SET_SYN_HOR
	@echo ""
	@echo "[31;1mWorking on: B_SYNTH_TIMES[m"
	@make --no-print-directory -C B_SYNTH_TIMES
	@echo ""
	@echo "[31;1mWorking on: START_REAL[m"
	@make --no-print-directory -C START_REAL
	@echo ""

clean:
	@echo "[31;1mWorking on: 0_SELECT_DATA[m"
	@make --no-print-directory -C 0_SELECT_DATA clean
	@echo "[31;1mWorking on: 2_RAY_DENSITY[m"
	@make --no-print-directory -C 2_RAY_DENSITY clean
	@echo "[31;1mWorking on: 4_TETRAD[m"
	@make --no-print-directory -C 4_TETRAD clean
	@echo "[31;1mWorking on: 6_MATR[m"
	@make --no-print-directory -C 6_MATR clean
	@echo "[31;1mWorking on: 8_3D_MODEL[m"
	@make --no-print-directory -C 8_3D_MODEL clean
	@echo "[31;1mWorking on: A_SET_SYN_VER[m"
	@make --no-print-directory -C A_SET_SYN_VER clean
	@echo "[31;1mWorking on: START_SYNTH[m"
	@make --no-print-directory -C START_SYNTH clean
	@echo "[31;1mWorking on: 1_3D_LOCATE[m"
	@make --no-print-directory -C 1_3D_LOCATE clean
	@echo "[31;1mWorking on: 3_GRID[m"
	@make --no-print-directory -C 3_GRID clean
	@echo "[31;1mWorking on: 5_SOSEDI[m"
	@make --no-print-directory -C 5_SOSEDI clean
	@echo "[31;1mWorking on: 7_INVERS[m"
	@make --no-print-directory -C 7_INVERS clean
	@echo "[31;1mWorking on: A_SET_SYN_HOR[m"
	@make --no-print-directory -C A_SET_SYN_HOR clean
	@echo "[31;1mWorking on: B_SYNTH_TIMES[m"
	@make --no-print-directory -C B_SYNTH_TIMES clean
	@echo "[31;1mWorking on: START_REAL[m"
	@make --no-print-directory -C START_REAL clean
