all:
	@echo "[31;1mWorking on: 1_SELECT[m"
	@make --no-print-directory -C 1_SELECT
	@echo ""
	@echo "[31;1mWorking on: 2_REFTABLE[m"
	@make --no-print-directory -C 2_REFTABLE
	@echo ""
	@echo "[31;1mWorking on: 3_LOCATE[m"
	@make --no-print-directory -C 3_LOCATE
	@echo ""
	@echo "[31;1mWorking on: 4_MATR[m"
	@make --no-print-directory -C 4_MATR
	@echo ""
	@echo "[31;1mWorking on: 5_INVERS[m"
	@make --no-print-directory -C 5_INVERS
	@echo ""
	@echo "[31;1mWorking on: START_1D[m"
	@make --no-print-directory -C START_1D
	@echo ""

clean:
	@echo "[31;1mWorking on: 1_SELECT[m"
	@make --no-print-directory -C 1_SELECT clean
	@echo "[31;1mWorking on: 2_REFTABLE[m"
	@make --no-print-directory -C 2_REFTABLE clean
	@echo "[31;1mWorking on: 3_LOCATE[m"
	@make --no-print-directory -C 3_LOCATE clean
	@echo "[31;1mWorking on: 4_MATR[m"
	@make --no-print-directory -C 4_MATR clean
	@echo "[31;1mWorking on: 5_INVERS[m"
	@make --no-print-directory -C 5_INVERS clean
	@echo "[31;1mWorking on: START_1D[m"
	@make --no-print-directory -C START_1D clean
