#!/bin/bash

comp=""
for d in 1_SELECT  2_REFTABLE  3_LOCATE  4_MATR  5_INVERS START_1D
do
 [ -d $d ] && echo "Working on: $d" || continue
 if [ -f ./CONFIG/$d ] 
 then 
   source ./CONFIG/$d
   unset LIBS
 else 
   echo " W:> No config file $d"
 fi
  
 cd $d
 #[ -f Makefile ] && mv Makefile Makefile.old
 OBJ=`ls -1 *.f90 | sed -e 's/.f90/.o/g' | tr "\n" " "`

 cat << EOF > Makefile
include ../../Makerules
OBJ=$OBJ
OBJ+=$EXTRAOBJ
BIN=$BIN

%.o:%.f90
	\$(FC) -c \$(FFLAGS) \$<

all: compile

compile: \$(OBJ)
	\$(FC)  \$(FFLAGS) -o \$(BIN) \$(OBJ) \$(LIBS) 

clean:
	@rm -f *.o \$(BIN)

fullclean: clean
	@rm \$(BIN)

install:
	@cp \$(BIN) \$(DESTDIR)

EOF
 comp="$comp $d"
 cd - > /dev/null
done

echo "all:" > Makefile
for d in $comp
do
 echo -e "\t@echo -e \"\e[31;1mWorking on: $d\e[m\"" >> Makefile
 echo -e "\t@make --no-print-directory -C $d" >> Makefile
 echo -e "\t@echo \"\"" >> Makefile
done

echo "" >> Makefile
echo "clean:" >> Makefile
for d in $comp
do
 echo -e "\t@echo -e \"\e[31;1mWorking on: $d\e[m\"" >> Makefile
 echo -e "\t@make --no-print-directory -C $d clean" >> Makefile
done



